### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by JohnCage1** [KalmAndKollected/HD2-DLL-PROXY-POC#2]
Which folder do I put the file into?

**Comment by KalmAndKollected** [comment]
You originally have to put the version.dll next to the game's exe, but that is pretty much outdated and detected already since they updated the anti-cheat measures. You need have to find a way to inject it into the game without being detected. Check FearlessRevolution Helldivers 2 Forum or UnknownCheats Helldivers 2 Forum, they have a few ways to inject the cheat into the game.
